name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for discovering this issue, can you fix this and send a PR?'' first issue'
        pr-message: 'Thank you for sending a pull request, I will look through and merge if need be'' first pr'
